### ISSUE TITLE
Speakers: Guðmundur Bjarni

### ISSUE THREAD

**Issue by axelg12** [jsis/monthly-meetup#11]
Would be talking about Heroku stuff @gudmundur

**Comment by gudmundur** [comment]
@axelg12 The only JS related topic I can think of is how to deploy and work with Node on Heroku, but I believe @omarkj did that recently.

I'm either thinking:
1. Workflows with GitHub & Heroku. Mostly going through our integration and show Review Apps.
2. How we build our internal services. Would touch on 12factor.net, JSON Schemas, logging and such.

What do you think?

**Comment by jonrh** [comment]
I'd personally be very interested in the GitHub and Heroku workflow. I've never had the time/chance to try out Heroku but I've heard about your Git integration. Specifically I'd b e curious to see the automatic deployment on push in practise.

**Comment by kristjanmik** [comment]
It doesn't have to be hardcore JS, nr. 2 sounds very interesting!

**Comment by koddsson** [comment]
I'm really interested in how you build your internal services!

**Comment by gudmundur** [comment]
By the way, is there a date and time set for this yet?

**Comment by kristjanmik** [comment]
@gudmundur we are aiming for 3rd week of July. We are waiting for a confirmation from the host.

**Comment by gudmundur** [comment]
@kristjanmik Thanks, keep me posted so I can try to fit this to my vacation schedule.

**Comment by axelg12** [comment]
@gudmundur The confirmed date is the July 23 at Quiz Up. Does that work for you ?

**Comment by kristjanmik** [comment]
starting at 17:30

**Comment by gudmundur** [comment]
@axelg12 @kristjanmik LGTM.

**Comment by kristjanmik** [comment]
@gudmundur Do you have a name for your talk?

**Comment by gudmundur** [comment]
@kristjanmik Current title is "Logs as data".

**Comment by gudmundur** [comment]
@kristjanmik @axelg12 Thanks for setting this up.

**Comment by gudmundur** [comment]
@jonrh If you'd like to meet up for coffee and have me give you a quick rundown of some stuff, then let me know.
