### ISSUE TITLE
Speakers: Guðmundur Már

### ISSUE THREAD

**Issue by axelg12** [jsis/monthly-meetup#12]
Would be talking about the Dohop hackathon hosted in march. @gudmundurmar

**Comment by koddsson** [comment]
Dohop's having a hackathon? Where do I sign up!?

**Comment by gudmundurmar** [comment]
@koddsson Það var hackathon um miðjan mars og @axelg12 tók meðal annars þátt. Fengu 5 daga til að gera eitthvað http://www.dohop.com/hackathon/. Ég postaði um það á Forritarar á Íslandi og íslensk vefhönnun (hefði greinilega þurft að gera meira til að koma því á framfæri, geri það næst). @axelg12 Ekkert mál að henda einhverju áhugaverðu saman um hackathon-ið.

**Comment by koddsson** [comment]
Ah nei, ég man eftir því núna. Ég var í Kaliforníu á þeim tíma og missti af því

**Comment by kristjanmik** [comment]
@gudmundurmar það væri snilld. Dugar 10mín slot?

**Comment by gudmundurmar** [comment]
@kristjanmik Get talað eins lengi og hentar um þetta. Stefnum bara á það og ég læt vita ef ég fer eitthvað yfir 10 mín

**Comment by kristjanmik** [comment]
@gudmundurmar ertu kominn með nafn á talkið?

**Comment by gudmundurmar** [comment]
@kristjanmik Ah, búinn að vera veikur síðustu daga en hendi inn nafni á það hérna á eftir. 
Verður líklega eitthvað svona...

### Pros and Cons of Hackathons

_Dohop's first hackathon: Expectations, Results, and Lessons_

Eða 

### Hackapros vs. Hackacons

Ég veit, ég veit... [brandarabann](http://qz.com/304268/why-china-is-now-banning-puns/)

**Comment by gudmundurmar** [comment]
Höfum þetta bara 

### Hackapros vs. Hackacons

_Dohop's first hackathon: Expectations, Results, and Lessons_

**Comment by kristjanmik** [comment]
:+1:
