### ISSUE TITLE
Speakers: Short talk from Aranja

### ISSUE THREAD

**Issue by kristjanmik** [jsis/monthly-meetup#13]
@eirikurn don't you have something cool to talk about for 5 or 10 minutes?

**Comment by davidblurton** [comment]
I have some stuff I could say about my Icelandic api. It would be about leveldb and docker.

**Comment by kristjanmik** [comment]
@davidblurton sounds great! How long slot do you need for the talk? I know a lot of people want to hear about both docker and leveldb :+1:

**Comment by davidblurton** [comment]
I think 10 minutes would be fine.

**Comment by kristjanmik** [comment]
Awesome! I will update this issue when we know the exact timing of the event.

**Comment by kristjanmik** [comment]
@davidblurton The confirmed date is the July 23. The event will start at 17:30, does that work for you?

**Comment by davidblurton** [comment]
Yup, that's great.

**Comment by kristjanmik** [comment]
Do you have a name for your talk @davidblurton ?

**Comment by davidblurton** [comment]
Working on it now so I'll send you something by the end of the day.

**Comment by davidblurton** [comment]
The title of the talk is `Building an API for Icelandic.`

**Comment by kristjanmik** [comment]
:+1:
