### ISSUE TITLE
Speakers: Axel Örn

### ISSUE THREAD

**Issue by koddsson** [jsis/monthly-meetup#14]
@ikornaselur would you be up for talking about perceptual visual diffing if there's a slot open for that?

**Comment by ikornaselur** [comment]
I definitely want to do that talk, but not for the next meetup in July - I would like more time to work on this (related to our discussion this weekend) before having a talk about this. The next meetup would probably be more preferable to me.

**Comment by kristjanmik** [comment]
@ikornaselur awesome, can you put something down in the next few weeks regarding your talk? We can use this issue to track it.

**Comment by kristjanmik** [comment]
@Ikornaselur  Are you ready to give your talk on the meetup the 17th of September?

**Comment by ikornaselur** [comment]
Yes! Sorry for the lack of info from me, I'm planning on having my talk on this months meetup. I will try to have info here this weekend.

**Comment by kristjanmik** [comment]
There are many events on the 17th of September so we are thinking about moving it by one week, to the 24th of September. Is that ok with you @Ikornaselur ?

**Comment by ikornaselur** [comment]
I thought I had been noticing many events on the 17th for the past few days.. 24th works just fine for me.

**Comment by kristjanmik** [comment]
Awesome!

**Comment by ikornaselur** [comment]
Btw, I should have had the talk name ready ages ago, it's simply 'Perceptual Difference Testing'. @kristjanmik

**Comment by ikornaselur** [comment]
@kristjanmik: what display connection options will I have? Just wondering if I need and then what adapter I should take for my mac.. Also, can we show up earlier to test out the setup so we don't have to do it when everyone has already arrived?

**Comment by kristjanmik** [comment]
I'm here all day so feel free to show up whenever you want. Regarding the setup I know that we have HDMI at least. I will post back here when I know exactly what is available.

**Comment by ikornaselur** [comment]
HDMI is good enough for me, since there's a HDMI port on my mac. I will show up at least earlier than 20:00 tomorrow, so I'll see you then!

**Comment by kristjanmik** [comment]
Awesome :+1: There is also a VGA display connection available.

**Comment by ikornaselur** [comment]
One more thing.. 4:3 or 16:9 projector?

**Comment by kristjanmik** [comment]
It is a 16:9 one
