### ISSUE TITLE
New format

### ISSUE THREAD

**Issue by kristjanmik** [jsis/monthly-meetup#2]
It would be nice to have more variations in the talks that we currently have. I suggest that we add these formats to the mix:
- Lightning talks
- I'm hiring/I need a job
- Tech stories
- Startup stories

**Comment by axelg12** [comment]
Agree with this one. Use JS to combine people but get this allows for more variations of speakers :+1:

**Comment by axelg12** [comment]
One idea I would like to propose is to have the JS meet up always at a certain time a month, if possible. I would say the third Thursday each month. This way it is easy to tell companies and speakers when we would like them to host/speak when planning ahead

**Comment by kristjanmik** [comment]
I like that, lets set that in place for the August meetup. It is much easier now since we have all those companies willing to host and we can simply cherry pick those who can host at that time.

**Comment by kristjanmik** [comment]
Since we are aiming for week 3 of each month I will close this down.
