### ISSUE TITLE
Speaker: Einar Norðfjörð

### ISSUE THREAD

**Issue by kristjanmik** [jsis/monthly-meetup#22]
@nordfjord is very passionate about [Mithrill.js](https://lhorie.github.io/mithril/). Are you willing to talk on the nest meetup?

**Comment by nordfjord** [comment]
Definitely :), looking forward to it.

**Comment by jonrh** [comment]
Awesome! Mithril was one of the libraries/frameworks I evaluated for a new project about a year ago. Ultimately I went for React but Mithril came in about 2nd or 3rd place of suitability for the project. I'm really intrigued by the simplicity and blazing speeds it boasts.

**Comment by kristjanmik** [comment]
@nordfjord Are you ready to give your talk on the meetup the 17th of September?

**Comment by nordfjord** [comment]
Come hell or high water ;)

**Comment by kristjanmik** [comment]
There are many events on the 17th of September so we are thinking about moving it by one week, to the 24th of September. Is that ok with you @nordfjord  ?

**Comment by nordfjord** [comment]
absolutely
