### ISSUE TITLE
August meetup sponsor

### ISSUE THREAD

**Issue by koddsson** [jsis/monthly-meetup#25]
There are some issues in the tracker for sponsors. Are any of them ready for us sometime in August?

Also do we need to get someone to record the talks for us if the future host doesn't have the equipment that QuizUp had?

@kristjanmik @axelg12 @MiniGod

**Comment by kristjanmik** [comment]
@koddsson we should ping quizup and ask if we can borrow the gear they had.
I'm in discussion with Tempo (#3) regarding August. I know both Betware and Microsoft can't host us then. I also think Vivaldi needs more time to plan this. What was the Qlik status @axelg12?

**Comment by axelg12** [comment]
Qlik said they were moving into their new office space in the end of the summer and were willing to host us then.  I would recommend pinging them for September or October?

**Comment by kristjanmik** [comment]
Offer them October, and we might give Betware the spot in Sept

**Comment by axelg12** [comment]
This all ties into the bimonthly theme #32. If we are holding the meetups bimonthly we would only need August, October and December.  So if we offer Qlik October we still have Tempo, Betware and Advania

**Comment by kristjanmik** [comment]
We should go for it. However August does not look that good tbh, no leads are getting back to me. Has someone replied to you guys @axelg12 @koddsson ?

**Comment by koddsson** [comment]
Nah. Wanna go for the October one instead?
