### ISSUE TITLE
Speaker: Jökull / Lemonade

### ISSUE THREAD

**Issue by jokull** [jsis/monthly-meetup#26]
Could talk about 
- Redux (specifically, the idea of reducers)
- Webpack
- `/api` proxy pattern
- CSS Modules (very cool!)

**Comment by jokull** [comment]
I could also do non-tech talks, origins of Lemonade, the startup scene in London, fundraising abroad etc.

**Comment by koddsson** [comment]
I'd be interested in webpack, css modules, origins of lemonade and fundraising abroad! 

In any case I'll add you to the august meetup schedule!

**Comment by jokull** [comment]
I’m abroad for most of august. My Reykjavík dates: august 17-21.

**Comment by koddsson** [comment]
Ok we haven't decided on a date yet since we're working on getting sponsors to host us right now.

If the date ends up being earlier in the month I'll move you to the September schedule :wink:

**Comment by kristjanmik** [comment]
@jokull we have had a growing interest in the topic of starting a tech startup. I think a lot of people would be interested in your point of view on that topic :+1:. On the other hand all of your suggested topics sound good!

**Comment by jokull** [comment]
:balloon:

**Comment by kristjanmik** [comment]
@jokull Are you ready to give your talk on the meetup the 17th of September?

**Comment by jokull** [comment]
No I’ll be abroad. I’m sorry.

**Comment by kristjanmik** [comment]
How about 22nd of October(#39) ?

**Comment by jokull** [comment]
Should work!

**Comment by kristjanmik** [comment]
Wohoo :fireworks: , I moved you to October :)

**Comment by axelg12** [comment]
@jokull Are you down for october 22nd ?

**Comment by koddsson** [comment]
CSS modules! :tada:
