### ISSUE TITLE
Sponsor: Advania

### ISSUE THREAD

**Issue by axelg12** [jsis/monthly-meetup#27]

**Comment by kristjanmik** [comment]
@axelg12 did you reach out to them already?

**Comment by axelg12** [comment]
Yes I've reached out. Will keep you posted

**Comment by axelg12** [comment]
Við erum alveg tilbúin að halda svona hitting aftur, en ágúst er eiginlega ekki góður tími, hvaða aðrir mánuðir kæmu til greina?

What month should I ask them about ?

**Comment by kristjanmik** [comment]
Offer them November?

**Comment by axelg12** [comment]
I already asked them for October, aiming for the bimonthly theme #32. With that we would need to get August, October and December. Sigrún is on a holiday though until the 15 of august.

**Comment by axelg12** [comment]
Sent another email, asking for September if possible.

**Comment by axelg12** [comment]
Advania said late September might for them ! 
"Hæ, hæ,
Já, það gæti vel gengið.
Hvaða dagsetning væri þetta? 
Við myndum fara í nánari skipulagningu með ykkur eftir haustráðstefnuna okkar, sem er 4. Sept, þar sem það er allt á floti núna hjá okkur vegna hennar."

@kristjanmik should I offer them 3rd week of September ?

**Comment by kristjanmik** [comment]
Awesome! Shouldn't we aim for the second week since it has been so long since our last one? What about the 10th of September?

**Comment by axelg12** [comment]
Tried asking for the 10th but they said it was too early. Go for the 24th ?

**Comment by axelg12** [comment]
Advania will host on the 17th !  :tada:

**Comment by koddsson** [comment]
:fireworks: :balloon: :confetti_ball:

**Comment by koddsson** [comment]
Will they have a talk to go into the TBA slot in the September schedule or is it up for grabs @axelg12?

**Comment by axelg12** [comment]
Don't know, I'll contact Sigrún after this week because of their conference. Do you have anyone in mind ?

**Comment by koddsson** [comment]
I think @alexcouper has a talk he want's to do so I was wondering if he should do a PR against the September schedule or the October one.

**Comment by kristjanmik** [comment]
I'm closing this issue down. Please redirect all non-advania related talk to #38
