### ISSUE TITLE
Bimonthly instead of monthly?

### ISSUE THREAD

**Issue by MiniGod** [jsis/monthly-meetup#32]
We should consider making these meetups bimonthly.
There is a lot of work that goes into putting these meetups together, and even if we manage to put together a meetup for August, it will most likely be late in the month, and we won't have time to put together the September meetup.
I just wanted to throw this thought out there.

_please hate on me if my logic is way off_

/cc @koddsson @kristjanmik @axelg12

**Comment by kristjanmik** [comment]
I think it is a good idea. Judging by how big this event has become we might need more time to organize them. We could also squeeze in other events every other month.

**Comment by axelg12** [comment]
Should we aim for a bimonthly after the next meetup or to aim to have the next one in September instead of August ?

**Comment by koddsson** [comment]
Personally leaning towards after this next meetup.

**Comment by MiniGod** [comment]
I agree with @axelg12. I think we should go for September, November, January, etc... Odd numbered months. December might be a little tight? Considering last 2 weeks are pretty much a no-go.
Related to [latest comment](https://github.com/jsis/monthly-meetup/issues/25#issuecomment-127773833) in #25.
