### ISSUE TITLE
So, no meeting this month?

### ISSUE THREAD

**Issue by JJ** [jsis/monthly-meetup#35]
I'm visiting next week, will there be a meeting next Wednesday?

**Comment by kristjanmik** [comment]
Most likely there won't be a large monthly meetup this month but there is a weekly RVK.js meetup every Wednesday http://rvkjs.com. Feel free to attend!

**Comment by JJ** [comment]
Thanks!

2015-08-16 13:48 GMT+02:00 Kristján Ingi Mikaelsson <
notifications@github.com>:

> Most likely there won't be a large monthly meetup this month but there is
> a weekly RVK.js meetup every Wednesday http://rvkjs.com. Feel free to
> attend!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jsis/monthly-meetup/issues/35#issuecomment-131530908.

## 

JJ
