### ISSUE TITLE
Speaker: Alex Couper

### ISSUE THREAD

**Issue by alexcouper** [jsis/monthly-meetup#37]
As @koddsson mentioned in https://github.com/jsis/monthly-meetup/issues/27, I am up for giving a talk at an upcoming monthly meetup.

The talk would have almost nothing to do with JS.

A working title might be "Introduction to kubernetes to make your microservices manageable."

I've not attended a JSMeetup, so some guidelines on length of talk, familiarity with things like docker would be useful. 

Also, feel free to say "this talk has already been given, so thanks but no thanks".

Is this even a talk that makes sense to give at JS meetup?

**Comment by kristjanmik** [comment]
We are very casual about the JS title, it was only put in place to rally people around something. The topic of your talk sounds interesting. Most people who attend are working on the frontend but we have a lot of backend/linux people attending as well. Therefore most of the crowd is probably familiar with Docker although many have probably not seen it in action.

The timeslot ranges from 5-20 minutes, how long do you think your talk will be? 

Are you ready to give your talk on the meetup the 17th of September?

**Comment by alexcouper** [comment]
Yeah I'm up for the 17th.

I'm yet to prepare anything, but I'd guess i'd be in the 10-15 minute range.

I assume that I can have internet connectivity during the talk?

**Comment by axelg12** [comment]
Yes I assume we can get some internet access.

**Comment by kristjanmik** [comment]
There are many events on the 17th of September so we are thinking about moving it by one week, to the 24th of September. Is that ok with you @alexcouper ?

**Comment by alexcouper** [comment]
@kristjanmik that actually works better for me.

**Comment by kristjanmik** [comment]
awesome!
