### ISSUE TITLE
October 22nd meetup by Novomatic

### ISSUE THREAD

**Issue by kristjanmik** [jsis/monthly-meetup#39]
Since Novomatic is hosting us in October I'm closing down #9.

We have to find some speakers to talk on this event.

**Comment by kristjanmik** [comment]
@axelg12 did you ask them to provide one inhouse talk?

**Comment by axelg12** [comment]
Yes they will provide one inhouse talk.

**Comment by kristjanmik** [comment]
:+1:

**Comment by koddsson** [comment]
I'm sorry to have missed this, gonna try extra hard to show up for the next one. :tada:
