### ISSUE TITLE
A talk from Vivaldi

### ISSUE THREAD

**Issue by kristjanmik** [jsis/monthly-meetup#42]
Vivaldi has accepted to deliver one talk on the 24th of September meetup.

**Comment by ltgorm** [comment]
I could talk about how we use React with Flux and how we try to get to a better TDD state of things with ReactTestUtils.
I could also talk about the mail client we are building using js libraries from whiteout and Dexie layer on top of IndexedDB.
Any preferences?

**Comment by koddsson** [comment]
:+1: on IndexedDB and :+1: on TDD w/ ReactTestUtils from me.

**Comment by koddsson** [comment]
:tada:
