### ISSUE TITLE
Meetup Sponsorship Program - Modulus

### ISSUE THREAD

**Issue by MiniGod** [jsis/monthly-meetup#43]
Ran across this: https://modulus.io/meetup-program

I know very little of it, or whether it applies internationally.

**Comment by kristjanmik** [comment]
We should look into it and apply if we qualify!

**Comment by axelg12** [comment]
Awesome !  We should definitely take a better look at this

**Comment by MiniGod** [comment]
The link is dead and I can't find one that works. Might be gone.

**Comment by kristjanmik** [comment]
@MiniGod giving money is not sustainable 😂. If someone ends up in here you could take a look at https://communityfund.co
