### ISSUE TITLE
Speaker / Panel: ES6

### ISSUE THREAD

**Issue by axelg12** [jsis/monthly-meetup#44]
Idea to have a panel about something interesting instead of the normal lecture. 

@kristjanmik came up with the idea to have the first panel about ES6 with some prepared questions like:
- What is ES6?
- Why should I move to ES6?
  -- Biggest advanced ?
  -- Biggest drawback ?
  -- Starting point
- Interaction with .JSX
- Babel, what is it and why is it used with ES6
- Thoughts on ES7?

I know that @arnarthor is willing to talk about this topic. 

What's your opinion ?

**Comment by koddsson** [comment]
Sounds awesome. There is maybe no need to include jsx in there other than a small note of it (maybe in the context of transpilers) but I'd leave that up to the speaker to decide on including it or not :stuck_out_tongue_winking_eye:

**Comment by axelg12** [comment]
Árni Fannar from Takumi said he would be interested and he also had a friend from Tempo in mind. @arnif

**Comment by kristjanmik** [comment]
Cool! I also pinged @krummi from @ozinc. Lets see if they have someone that is willing to participate.

**Comment by koddsson** [comment]
:tada:
