### ISSUE TITLE
November meetup?

### ISSUE THREAD

**Issue by koddsson** [jsis/monthly-meetup#49]
It's never too soon to start planning! :calendar:

The obvious thing we need to do is find a place to host us. Previously we've contacted a bunch of companies that have been willing so maybe we need to check those guys again, I've already emailed [Íslandsbanki](#29) and if any of you are busy I can email any other leads.

**Comment by koddsson** [comment]
Somebody was mentioning that we could have a 'showdown' of some-sorts with Native apps vs. Web apps. I thought that might be very :cool:

**Comment by kristjanmik** [comment]
More like, it will be very :hotsprings:

**Comment by koddsson** [comment]
Íslandsbanki is out for November so we need to find some place else!

**Comment by koddsson** [comment]
Whoops

**Comment by koddsson** [comment]
:calendar: :calendar: :calendar: :calendar: :calendar:
