### ISSUE TITLE
A facilitator

### ISSUE THREAD

**Issue by kristjanmik** [jsis/monthly-meetup#5]
A facilitator is a person who introduces everyone and makes sure the schedule is on track.
I personally want to step down from that role since I want to do more presentations/talks.

**Comment by axelg12** [comment]
I suggested to @koddsson earlier today that he would be the facilitator. What do you say @koddsson ?

**Comment by koddsson** [comment]
Sure! Sounds fun :)

**Comment by kristjanmik** [comment]
@koddsson awesome, you will facilitate the first one ;)

**Comment by koddsson** [comment]
Since that's all settled I'm closing this!
