### ISSUE TITLE
Sponsor: Betware

### ISSUE THREAD

**Issue by axelg12** [jsis/monthly-meetup#9]
Reached out to check if they would be interested.

**Comment by kristjanmik** [comment]
When I talked to [Björn](https://www.facebook.com/bjorn.ingimundarson?fref=ts) about this a while back he said that they were very interested. It might be good to involve him(I don't know his github handle).

**Comment by axelg12** [comment]
Betware is willing to host August or later. I said we would be in touch

**Comment by axelg12** [comment]
I asked them for September or October

**Comment by axelg12** [comment]
Betware are down with October if we want

@kristjanmik

**Comment by kristjanmik** [comment]
@axelg12 Awesome! Sign them up!

**Comment by axelg12** [comment]
22 October :100:

**Comment by kristjanmik** [comment]
Awesome!

**Comment by kristjanmik** [comment]
Please use #39 for planning.
